import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black text-white`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
